apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: datagrid
spec:
  dependencies:
    volumeClaimName: datagrid-lib-pvc
  expose:
    type: LoadBalancer
  replicas: 2
  security:
    endpointAuthentication: false
  service:
    type: DataGrid
