apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: datagrid
spec:
  image: quay.io/infinispan/server:12.0.2.Final-1
  dependencies:
    volumeClaimName: datagrid-lib-pvc
  expose:
    type: LoadBalancer
  # TODO Increase when pvc mounting issue is resolved in operator
  replicas: 1
  security:
    endpointEncryption:
      type: None
    endpointAuthentication: false
  service:
    type: DataGrid
