apiVersion: v1
kind: Pod
metadata:
  name: datagrid-lib-pod
spec:
  volumes:
    - name: lib-pv-storage
      persistentVolumeClaim:
        claimName: datagrid-lib-pvc
  containers:
    - name: lib-pv-container
      image: quay.io/infinispan/server:12.0
      volumeMounts:
        - mountPath: "/tmp/libs"
          name: lib-pv-storage
