name: matchstart
namespace: ""
runtime: quarkus
image: quay.io/ilawson/matchstart
imageDigest: ""
trigger: events
builder: quay.io/boson/faas-quarkus-jvm-builder
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder
envVars:
  WATCHMAN: http://watchman-battleships-backend.apps.summit-dev-aws.m7o7.p1.openshiftapps.com/watch